# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_auto_20180521_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw_hash',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
